package eu._4fh.guildsync.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

import javax.annotation.Nonnull;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import eu._4fh.guildsync.config.Config;

public class Transaction implements AutoCloseable {

	private static final Logger log = LoggerFactory.getLogger(Transaction.class);
	private static final ThreadLocal<Transaction> currentTransaction = new ThreadLocal<>();
	private static final Config config = Config.getInstance();

	private final @Nonnull Connection connection;
	private int usageCounter;

	private Transaction(final @Nonnull Connection connection) {
		try {
			connection.setAutoCommit(false);
			connection.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
		} catch (SQLException e) {
			try {
				connection.close();
			} catch (Throwable t) {
				// Ignore
			}
			throw new RuntimeException(e);
		}
		currentTransaction.set(this);
		this.connection = connection;
		usageCounter = 1;
		log.debug("BEGIN");
	}

	@Override
	public void close() {
		usageCounter--;
		if (usageCounter > 0) {
			return;
		}
		try {
			currentTransaction.remove();
			log.debug("END");
			connection.rollback();
			connection.close();
		} catch (SQLException e) {
			try {
				connection.close();
			} catch (Throwable t) {
				// Ignore
			}
			throw new RuntimeException(e);
		}
	}

	public void commit() throws SQLException {
		if (usageCounter != 1) {
			log.debug("Suppress commit, only most outer level can commit");
			return;
		}
		log.debug("COMMIT");
		connection.commit();
	}

	public static Transaction getTransaction() {
		Transaction transaction = currentTransaction.get();
		if (transaction != null) {
			transaction.usageCounter++;
			return transaction;
		}
		try {
			transaction = new Transaction(config.dbDataSource().getConnection());
			return transaction;
		} catch (SQLException e) {
			throw new RuntimeException(e);
		}
	}

	protected PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		log.debug("Prepare " + sql);
		return connection.prepareStatement(sql, autoGeneratedKeys);
	}

	protected PreparedStatement prepareStatement(String sql) throws SQLException {
		return prepareStatement(sql, Statement.NO_GENERATED_KEYS);
	}
}
